# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost:      15

    providers:
        my_provider:
          entity:
             class: AppBundle:User
             property: username

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /login
    access_control:
                - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/user/new, role: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/, role: [ROLE_USER, ROLE_ADMIN] }
                - { path: ^/user/list, role: ROLE_ADMIN }
                - { path: ^/user/*, role: ROLE_ADMIN }